image: node:14

pages:
  stage: deploy
  script:
    - mkdir -p public # Membuat direktori public jika belum ada
    - cp -r halaman/* public/ # Menyalin semua konten dari folder halaman ke public
  artifacts:
    paths:
      - public
  only:
    - main
